server:
  port: 8082

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/suppliers
    username: root
    password: codename47SUNBRO@239485672
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

scms:
  cors:
    origin: "http://localhost:5173/"